### ISSUE TITLE
Article: deployment to the basketball court

### ISSUE THREAD

**Issue by Westerby** [AlvinYH/Faster-VoxelPose#1]
Dear Authors,

thank you for publishing your ispiring work.
In the article you mention that you "deployed our model to a basketball court and a retail store". Did this model need any kind of retraining or finetuning to accout for new camera set-up or calibration?

Thank you

**Comment by AlvinYH** [comment]
Thanks for your question! We directly retrain the model for scenarios with different space sizes, as the number of voxels may be adjusted to maintain accuracy. However, theoretically speaking, if we merely replace the camera calibration parameters, there's no need to retrain the model from scratch.

**Comment by Westerby** [comment]
Thank you for the answer!
