### ISSUE TITLE
Where could i found the model_best.pth.tar？

### ISSUE THREAD

**Issue by xjchao7** [AlvinYH/Faster-VoxelPose#10]
Thank you very much for your perfect work.

When I would like test your code, I could not find the model_best.pth.tar. Could you please provide the model for testing.

Thanks.

**Comment by Whiplash-18** [comment]
> Thank you very much for your perfect work.
> 
> When I would like test your code, I could not find the model_best.pth.tar. Could you please provide the model for testing.
> 
> Thanks.

Hey, I have the same problem with you.
Have you solved the problem?
Thanks!

**Comment by LRuid** [comment]
me too. i have the same problem.

**Comment by LRuid** [comment]
> me too. i have the same problem.
you need train youself model before test

**Comment by AlvinYH** [comment]
Thanks for your interest in our work. We've modified the code and uploaded our pre-trained models. You can download the checkpoints on the current release webpage.
