### ISSUE TITLE
Inference time in the paper

### ISSUE THREAD

**Issue by Westerby** [AlvinYH/Faster-VoxelPose#11]
Dear authors,

I conducted several tests and can't reproduce the FPS metric you mention in "Table 3: Comparison with SOTA on Panoptic".

My specs:
Python 3.6.10
torch.__version__: '1.4.0'
torch.version.cuda: '10.1'
GPU: Quadro RTX 6000
Batch size: 1

Example cameras, scene and frame:
Cameras list: ['00_03', '00_06', '00_12', '00_13'] 
Scene: 160906_pizza1
Frame: 00000347
Config: only difference: CAMERA_NUM: 4

The test I do is without data loading, just inference in the loop:

```
from imutils.video import FPS
fps = FPS().start()
for i in range(120):
    final_poses, poses, proposal_centers, _, input_heatmap = model(views=inputs, 
                                                                   meta=meta, 
                                                                   cameras=cameras,
                                                                   resize_transform=resize_transform)
    fps.update()

fps.stop()
print("[INFO] elasped time: {:.2f}".format(fps.elapsed()))
print("[INFO] approx. FPS: {:.2f}".format(fps.fps()))

[INFO] elasped time: 9.80
[INFO] approx. FPS: 12.24
```

The FPS I get is ~12, so considerably lower than ~30 that is claimed in the paper.
Am I missing something here?

Thank you!

**EDIT:**
I did the same test on another machine:
Python 3.6.13
torch.__version__: '1.7.1+cu110'
GPU: Tesla V100
Other parameters were the same

```
[INFO] elasped time: 11.99
[INFO] approx. FPS: 10.01
```

**Comment by AlvinYH** [comment]
Hello. Please note that following previous works, the off-the-shelf 2D pose estimator time is not measured for efficiency analysis, as mentioned in our paper. And in our implementation, we generate the 2D heatmaps in each loop without pre-processing. Therefore, you need to exclude that part of time cost when measuring the inference efficiency.

**Comment by Westerby** [comment]
Hello,
okay, I didn't catch that in the paper.
Thank you very much for your quick answer!
All the best and thanks for publishing your great work.
