### ISSUE TITLE
数据集下载不下来，

### ISSUE THREAD

**Issue by simple123456T** [AlvinYH/Faster-VoxelPose#14]
http://campar.in.tum.de/Chair/MultiHumanPose

this site can not  download the datasets.

help

**Comment by Walter0807** [comment]
Hi, we cannot distribute the dataset. Maybe you can refer to xrmocap (https://github.com/openxrlab/xrmocap/blob/main/docs/en/dataset_preparation.md) for help!

**Comment by nxxnxxnxx1** [comment]
campar.in.tum.de sames  closed ,help
