### ISSUE TITLE
如何用train好的模型去predict多角度照片？——来自新学者的疑问

### ISSUE THREAD

**Issue by graceforlife** [AlvinYH/Faster-VoxelPose#18]
感谢前辈将如此优美的代码共享，我有一个疑问，在readme里面，我可以找到train的用法，这是用来训练模型，还可以找到evaluate，这是用来评价模型的好坏。可是我从那里去predicate，比如我已经训练好了模型，然后我想用三种campus照片去通过训练好的模型融合出3d图片来。我该如何操作，谢谢！

**Comment by AlvinYH** [comment]
I believe you've asked the identical question in English and I also commented about your concern. So I'll close this issue.
