### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by Taylorminer** [AlvinYH/Faster-VoxelPose#20]
Thanks for your work！When I run "python run/train.py --cfg configs/campus/jln64.yaml". I meet the following problem:

![3](https://user-images.githubusercontent.com/41726592/210294055-948b802b-e729-4ba8-81b5-9d116f4cda75.png)

Can you help me ?

**Comment by Taylorminer** [comment]
> you should change the gpus field in the config to '0' , assuming you have 1 gpu on your system

Thanks for your reply !  I change this line "self.device = torch.device(int(cfg.GPUS.spilit(',')[0]))" in lib/models/human_detection_net.py into "os.environ['CUDA_VISIBLE_DEVICE'] = 0", self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu"). But I meet the following error:
![4](https://user-images.githubusercontent.com/41726592/210917044-a3336b7d-d89d-4f2b-a814-b41bac1c857f.png)

**Comment by gpastal24** [comment]
Hi, did you set the env variable yourself? I have trained the model both in a single and dual gpu setup, using gpus '0' and gpus '1' respectively, without changing the source code in places where the model is loaded onto the gpu

**Comment by Taylorminer** [comment]
> Hi, did you set the env variable yourself? I have trained the model both in a single and dual gpu setup, using gpus '0' and gpus '1' respectively, without changing the source code in places where the model is loaded onto the gpu

No, I don't set any variable by myself. When I train the model , it shows this error. How can you use gpus '0' and gpus '1' respectively, without changing the source code ?
