### ISSUE TITLE
the bounding box isn't sufficiently large to cover poses!

### ISSUE THREAD

**Issue by FrankMMMMMM** [AlvinYH/Faster-VoxelPose#25]
Thanks for your work！When I run "python run/train.py --cfg configs/campus/jln64.yaml". I meet the following problem:
![image](https://user-images.githubusercontent.com/92253265/234454447-5da31af5-90e4-47a7-a4cf-b2411f665bb1.png)
Can you help me to solve this problem?

**Comment by 1124792823** [comment]
same question

**Comment by FrankMMMMMM** [comment]
> same question

@1124792823 
Hi
That doesn't seem to be a problem.

**Comment by CH1-pix** [comment]
Hi!  How did you solve this problem?

**Comment by FrankMMMMMM** [comment]
@CH1-pix 
I didn't solve it.
But in fact you can ignore the problem. The experiment seems to work fine. Killed may be due to lack of computer performance. 

By the way, did you find any other code that does multi-camera target tracking?

**Comment by CH1-pix** [comment]
@FrankMMMMMM Thanks!!  On what GPUs did you complete the training? I can't do it with the RTX 3050 LAPTOP. Regarding your question, I remember that CVPR2023 has a related paper, you can go and take a look.

**Comment by FrankMMMMMM** [comment]
@CH1-pix 
I trained on the Campus dataset using an RTX2080TI in a cloud GPU environment.
