### ISSUE TITLE
3D Pose visualization

### ISSUE THREAD

**Issue by bj4-567** [AlvinYH/Faster-VoxelPose#31]
Thanks for your excellent work.
Can you provide the code about  project 3D pose to the 2d Image, like Fig5 in the paper?
Thanks a lot.
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/54530707/d31067ee-bca9-477c-9b07-c82561868c4b)

**Comment by bj4-567** [comment]
Hi, I find it on the vis.py. Thanks a lot!!!!!!!!!!!!!
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/54530707/0a840c36-fa9b-44c9-9538-b0274ef1a7d2)

**Comment by AlvinYH** [comment]
Thanks for your interest in our work. We've modified the code and you can pull the recent release. It's recommended to refer to `demo/visualize.ipynb` to check how to use visualization functions.
