### ISSUE TITLE
 I don't know why the performance is slightly lower when I execute the code following Readme.

### ISSUE THREAD

**Issue by qbxlvnf11** [AlvinYH/Faster-VoxelPose#38]
I continued learning by following Readme. (data preparation, preprocessing, using smae config file, etc.)
However, we found some performance degradation in all datasets.

- Downloaded weights (Panoptic)
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/52263269/a472e0b3-bb9b-463c-848f-6a66a79081dc)
- Train weights (Panoptic)
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/52263269/fbdc80c1-95c4-4667-80a9-45b1ab3bab0c)

- Downloaded weights (Shelf)
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/52263269/b23722f1-f26d-48f6-97de-f1fe8e4c7654)
- Train weights (Shelf)
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/52263269/6af784b4-b022-44ce-9a7a-1beb73024624)

- Downloaded weights (Campus)
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/52263269/ad6cbe92-ad69-44b4-90c0-982821191d43)
- Train weights (Campus)
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/52263269/4cbf6861-2056-4528-9f12-5345d9c7bba6)

I wonder if it's because I missed something in the process. (for examples, data argument set as true?)

**Comment by gpastal24** [comment]
@qbxlvnf11 I have also noticed the same thing.
In my case the 3D error is 19.2mm on Panoptic when training from scratch.
Campus and Shelf at 96.81 and and 97.51 PCK respectively.
Trained on RTX 3060 and 3080

**Comment by qbxlvnf11** [comment]
@gpastal24 
I see. I wonder if the currently provided pretrained weights were trained using a different code.

**Comment by qbxlvnf11** [comment]
Refer to https://github.com/AlvinYH/Faster-VoxelPose/issues/17

**Comment by gpastal24** [comment]
I don't think that's the issue here, since the author clearly states they used Pose ResNet , not HRNet

**Comment by JohnPekl** [comment]
In my case, I followed the README to run evaluation (inference, not training) and got a higher error MPJPE compared with yours; my output is `mpjpe@500mm: 57.998`. 

Download the [pretrained backbone model](https://drive.google.com/file/d/1Qlt_S5BoJcUIyXO5s6FEvVJ_ucQ1yN_L/view?usp=sharing)
Model weight: [Google drive](https://drive.google.com/file/d/1ETtd2isq11oiqqkEPfCQaOSmtU0MO9kH/view?usp=sharing)
Config: [cfg](https://github.com/AlvinYH/Faster-VoxelPose/blob/main/configs/panoptic/jln64.yaml)

Would you please let me know why?

```
=> the output will be saved in: output/panoptic/jln64
=> loading data...
Warning: detected an instance where the size of the bounding box is 2.24m, larger than 2m
=> 2580 images from 5 views loaded
=> constructing models...
=> save the 3D grid for feature sampling
=> loading weights of the backbone
=> load model state ../pretrained_weights/model_best.pth.tar

2025-07-17 18:37:18,067 => 2580 images from 5 views loaded
2025-07-17 18:37:20,645 => load model state ../pretrained_weights/model_best.pth.tar
2025-07-17 19:12:41,369 Evaluation results on Panoptic dataset:
ap@25: 0.0419	ap@50: 0.3421	ap@75: 0.7212	ap@100: 0.9260	ap@125: 0.9504	ap@150: 0.9573	recall@500mm: 0.9685	mpjpe@500mm: 57.998
```
