### ISSUE TITLE
visualize 

### ISSUE THREAD

**Issue by 1124792823** [AlvinYH/Faster-VoxelPose#39]
I'm using Faster-VoxelPose for a project, and I'm experiencing issues during the visualization stage. I suspect these issues might be related to incorrect camera calibration. The results I'm getting are not as expected, especially when using the Shelf and Campus datasets.

Could you please advise on the correct process for camera calibration in Faster-VoxelPose to ensure accurate visualization? Are there any specific parameters or calibration techniques that I should be aware of?

Any tips or common mistakes to avoid in this process would also be highly appreciated.

Thank you for your support.

**Comment by AlvinYH** [comment]
Hi, @1124792823.  Could you provide more details or screenshots showcasing the specific issues or bugs you're encountering? This will help us to understand the problem more clearly.

**Comment by 1124792823** [comment]
![1700467356365](https://github.com/AlvinYH/Faster-VoxelPose/assets/58672693/a065db9c-4859-4a6a-bbf2-c4aa606a89e9)

![1700467442520](https://github.com/AlvinYH/Faster-VoxelPose/assets/58672693/3b50b3ab-b9b5-4a0c-8307-27121ec055ad)

**Comment by 1124792823** [comment]
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/58672693/c9a91e89-e346-4071-bfd9-d2ebbb8f7b3c)
![image](https://github.com/AlvinYH/Faster-VoxelPose/assets/58672693/b020641c-bc30-49ed-a0a7-5054aa284fa3)

**Comment by fhxsa** [comment]
Could you tell me how to solve this problem, I also encountered the same problem
