### ISSUE TITLE
train failed,why all epoch display "NaN or Inf found in input tensor"?

### ISSUE THREAD

**Issue by iwsuccess** [AlvinYH/Faster-VoxelPose#4]
![faster](https://user-images.githubusercontent.com/50507649/186367060-f516aa82-20fe-4354-8b7c-fe59d310ee9d.PNG)
problem in here:
Epoch: 10
Epoch: [10][0/13]       Time: 0.613s (0.613s)   Speed: 39.1 samples/s   Data: 0.420s (0.420s)   Loss: nan (nan) Loss_2d: 0.0019247 (0.0019247)  Loss_1d: nan (nan)        Loss_bbox: 0.027619 (0.027619)  Loss_joint: nan (nan)   Memory 0.0
NaN or Inf found in input tensor.
NaN or Inf found in input tensor.
NaN or Inf found in input tensor.

all of training epoch like this,how to deal with it? 
i hope get the answer.thank you!

**Comment by AlvinYH** [comment]
Thanks for your interest in our project. We have fixed the bug in the previous commits. Please check out the newest version and let me know if there is any problem.

**Comment by iwsuccess** [comment]
Thanks for your reply.
i have another question,what is your python version?
my python version is 3.8. I have followed your latest requirements.txt. But I can not install opencv-python=3.4.2. 
Because python3.8 can not have opencv-python=3.4.2. The highest supported version is python3.7.
But python3.7 can not support numpy1.22.0.
so, i do not know how to configure the environment. Looking forward to your reply，thank you very much.

**Comment by AlvinYH** [comment]
Previously we use python 3.7 and NumPy 1.19.2 as stated in the requirements.txt. We've just noticed that the dependabot detected a security vulnerability in Numpy with a version lower than 1.22.  However, you can downgrade the version of python and Numpy, it should work fine.  Another way is to use a higher version of opencv-python. We'll fix this problem later and upload a correct requirement file. Thanks for pointing it out.

**Comment by iwsuccess** [comment]
thanks for your reply!
i downloaded your new published program and tried your advice.
first,i used python3.7,numpy1.19 and opencv-python3.4.2.17
then i used python3.8,numpy1.22 and opencv-python3.4.9.31
Errors occurred in both cases. 
![q1](https://user-images.githubusercontent.com/50507649/187064978-64c3d33a-d5ec-436e-b94f-5a15537cef85.png)
![q2](https://user-images.githubusercontent.com/50507649/187064990-eebf24db-92b1-4323-83cc-3e8dad5d8061.png)
So,Is it because the bounding box is set a little too small? Or something else? I still haven't run through the program. 
Looking forward to your reply.Thank you very much!

**Comment by AlvinYH** [comment]
Actually, the printed message about the bounding box doesn't suggest the occurrence of errors. It's simply a warning that the tight bounding box isn't large enough to cover poses in a few cases. You can increase the size of the bounding box. However, the growing size of voxels will introduce larger quantization errors. It's a trade-off between dealing with some corner cases and maintaining accuracy. The actual cause of errors here is that your PyTorch is not compatible with CUDA. You may have downloaded a version of PyTorch that only supports CPU.

**Comment by Vancouver-wen** [comment]
> ![faster](https://user-images.githubusercontent.com/50507649/186367060-f516aa82-20fe-4354-8b7c-fe59d310ee9d.PNG) problem in here: Epoch: 10 Epoch: [10][0/13] Time: 0.613s (0.613s) Speed: 39.1 samples/s Data: 0.420s (0.420s) Loss: nan (nan) Loss_2d: 0.0019247 (0.0019247) Loss_1d: nan (nan) Loss_bbox: 0.027619 (0.027619) Loss_joint: nan (nan) Memory 0.0 NaN or Inf found in input tensor. NaN or Inf found in input tensor. NaN or Inf found in input tensor.
> 
> all of training epoch like this,how to deal with it? i hope get the answer.thank you!



> ![faster](https://user-images.githubusercontent.com/50507649/186367060-f516aa82-20fe-4354-8b7c-fe59d310ee9d.PNG) problem in here: Epoch: 10 Epoch: [10][0/13] Time: 0.613s (0.613s) Speed: 39.1 samples/s Data: 0.420s (0.420s) Loss: nan (nan) Loss_2d: 0.0019247 (0.0019247) Loss_1d: nan (nan) Loss_bbox: 0.027619 (0.027619) Loss_joint: nan (nan) Memory 0.0 NaN or Inf found in input tensor. NaN or Inf found in input tensor. NaN or Inf found in input tensor.
> 
> all of training epoch like this,how to deal with it? i hope get the answer.thank you!



> ![faster](https://user-images.githubusercontent.com/50507649/186367060-f516aa82-20fe-4354-8b7c-fe59d310ee9d.PNG) problem in here: Epoch: 10 Epoch: [10][0/13] Time: 0.613s (0.613s) Speed: 39.1 samples/s Data: 0.420s (0.420s) Loss: nan (nan) Loss_2d: 0.0019247 (0.0019247) Loss_1d: nan (nan) Loss_bbox: 0.027619 (0.027619) Loss_joint: nan (nan) Memory 0.0 NaN or Inf found in input tensor. NaN or Inf found in input tensor. NaN or Inf found in input tensor.
> 
> all of training epoch like this,how to deal with it? i hope get the answer.thank you!

Hello, I meet the same "NAN" question as well.  I want to konw whether you have resolved the "NAN" problem. If you have solved the problem, could you send your correct code to me ? Thank you!
