### ISSUE TITLE
How to visualize the results for multi-person

### ISSUE THREAD

**Issue by xjchao7** [AlvinYH/Faster-VoxelPose#8]
Thank you for your perfect work. I have a question that how could i visualize the results for multi-person?

Thank you very much.

**Comment by AlvinYH** [comment]
Our code has already supported the visualization of multi-person pose estimation. Please refer to the **lib/utils/vis.py** for details.

**Comment by Xianjin111** [comment]
> Our code has already supported the visualization of multi-person pose estimation. Please refer to the **lib/utils/vis.py** for details.

Thank you very much.
