### ISSUE TITLE
Evaluate on the wild

### ISSUE THREAD

**Issue by ireneb612** [AlvinYH/Faster-VoxelPose#9]
Hi could we use this model on a never seen video?

**Comment by AlvinYH** [comment]
Thanks for your question. It depends. As our method is data-driven, if the poses of the individuals in an unseen video are common in our daily life (standing, sitting, running, etc.), the model shows promising transferability. Actually, for inference on the Shelf/Campus, we use a synthetic dataset `panoptic_training_pose.pkl` for training, which covers lots of poses and the large variation enables good generalization ability. You can adopt this scheme and only need to modify the parameters of environment settings/cameras. However, for complicated and difficult poses (acrobatics, yoga, professional dancing), it's hard to compensate for the distribution shift and training on specific dataset is recommended.
